### ISSUE TITLE
0.37.0 breaks!

### ISSUE THREAD

**Issue by kjartanm** [thgh/now-sapper#15]
Get the following in the zeit build log:

ReferenceError: entrypointFsDirname is not defined
--
11:41:38 AM | at Object.exports.build (/zeit/38d08f0642d626e1/.build-utils/.builder/node_modules/now-sapper/index.js:31:5)

**Comment by justinmoon** [comment]
I have same problem

**Comment by begonaalvarezd** [comment]
Same problem
