### ISSUE TITLE
Monorepo support?

### ISSUE THREAD

**Issue by rawgroundbeef** [thgh/now-sapper#17]
Thanks for this.

I can't make this work in a monorepo. Here's my `now.json`:

```
{
  "version": 2,
  "builds": [
    { "src": "my-sapper-app/package.json", "use": "now-sapper" }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "/my-sapper-app/$1" }
  ]
}
```

I'm not familiar with now builders yet. I thought I'd post this to see if maybe there were some trivial patch I could apply.

**Comment by Ungolim** [comment]
it's not about monorepos, seems to be about node engines v^

works only with v^8.x -> https://github.com/thgh/now-sapper/issues/11#issue-522843754

**Comment by rawgroundbeef** [comment]
Thanks @lepidotteri!

* use https://github.com/ajbouh/now-sapper/ if you need a Node version > 8.
* `now dev` still doesn't work either way. 🤷‍♂
