### ISSUE TITLE
PORT Set to 0 breaks SSR in preload

### ISSUE THREAD

**Issue by fpaboim** [thgh/now-sapper#20]
Any fetching on the `preload` function, e.g. as in the blog page, flashes a 500 error when loading. This can be observed with the template project going to the blog page and bringing up the network pane to inspect requests.

**Comment by thgh** [comment]
So this would basically fix #8? Will test soon!

**Comment by fpaboim** [comment]
> So this would basically fix #8? Will test soon!

Possibly related since it can't contact the host the the port specified before (0)

**Comment by thgh** [comment]
Released in v0.39.0!
