### ISSUE TITLE
Error deploying sapper-template

### ISSUE THREAD

**Issue by WHenderson** [thgh/now-sapper#3]
Hi,

I degit-ed the sapper template (`npx degit sveltejs/sapper-template#rollup sap03`), made the described changes (`README.md`) and attempted to build/deploy to now (`yarn run now`).

I keep getting the following:

> \> WARN! There are no files (or only files starting with a dot) inside your deployment.
> \> Error! You defined 1 build that did not match any source files (please ensure they are NOT defined in .nowignore):
> \- {"src":"__sapper__/build/index.js","use":"now-sapper"}
error Command failed with exit code 1.

Any help appreciated. I only just started using now so I can't use their v1 API.

**Comment by thgh** [comment]
Try this .nowignore:

```
__sapper__/dev
__sapper__/export
cypress
node_modules
src
```

Note: I only tested with the rollup-v3 branch
`npx degit sveltejs/sapper-template#rollup-v3 sap03`

**Comment by WHenderson** [comment]
It's working, fantastic!

Thanks so much for your help

**Comment by thgh** [comment]
Thanks for creating an issue!
