### ISSUE TITLE
Does this work with Vercel serverless functions?

### ISSUE THREAD

**Issue by joeybellerose** [thgh/now-sapper#30]
I'm able to get server routes to work locally but get a 500 error when I deploy to Vercel.
My folder structure looks like this:
![folderstructure](https://user-images.githubusercontent.com/28072958/82720748-863d4580-9c84-11ea-8922-cc8af1ffa304.png)

Here's my now.json file:
![now](https://user-images.githubusercontent.com/28072958/82720749-86d5dc00-9c84-11ea-96a6-9c8d575eddf6.png)

Here's my server.js file:
![server](https://user-images.githubusercontent.com/28072958/82720750-86d5dc00-9c84-11ea-8808-37bfdd9caad9.png)

**Comment by benmccann** [comment]
@joeybellerose can you provide any more details about what the error is?

**Comment by benmccann** [comment]
Also, I see you have a `now.json`. Are you running the `vercel` command? I wonder if maybe it'd need to be updated to `vercel.json`?

**Comment by joeybellerose** [comment]
@benmccann The error i get is 500 "Unexpected token O in JSON at position 0"

I have been running the `vercel` command and tried changing to `vercel.json` to no avail.

Also...it looks like vercel recognizes a function named `index` but i have no idea where that is coming from.

**Comment by thgh** [comment]
That `index` is the function that runs serverless https://github.com/thgh/now-sapper/blob/master/index.js#L73)

The screenshots look ok, what happens when you visit `/company/ticker.json` ? It looks like that response might contain an error that will help you further.

**Comment by joeybellerose** [comment]
@thgh Thanks for the clarification. I get the following response when I visit `/company/ticker.json`:  

> Only absolute URLs are supported

Also in `[ticker].svlete` my fetch looks like this `const res = await this.fetch(`company/${ticker}.json`);`

Does this help?

**Comment by thgh** [comment]
You probably want this instead: (note the URL starting with `/`)
```
this.fetch(`/company/${ticker}.json`);
```

**Comment by joeybellerose** [comment]
@thgh Thanks so much!  That did the trick.....I also overlooked that you need to have environment variables for Production as well as Preview.  Thanks again for all the help!
