### ISSUE TITLE
Error: Couldn't find your server instance. Did you write `module.exports = app`?

### ISSUE THREAD

**Issue by ryanditjia** [thgh/now-sapper#31]
Hi, I’m getting an error that seems like a false negative.

The error is:

> This is now-sapper, your Vercel builder. Turns out we couldn't find your server instance. Did you write `module.exports = app`?
>
> Read the docs or create an issue: https://github.com/thgh/now-sapper

My `server.js` looks as follows.

```server.js
const app = polka() // You can also use Express
// …

export default app
```

**Comment by ryanditjia** [comment]
Looks like [this](https://github.com/sveltejs/sapper-template-rollup/commit/c5bd6f061c80531ecfdd4444457fb6d865f7f34d) was it.

This problem happens if the server portion of your `rollup.config.js` you have 		`preserveEntrySignatures` set to false.

**Comment by thgh** [comment]
For future reference:
```js
// Is NOT preserved when preserveEntrySignatures: false
export default app

// Is preserved when preserveEntrySignatures: 'strict'
export default app

// Is preserved when preserveEntrySignatures: false
module.exports = app

// Is preserved when preserveEntrySignatures: 'strict'
module.exports = app
```
