### ISSUE TITLE
Update demo

### ISSUE THREAD

**Issue by benmccann** [thgh/now-sapper#33]
The README links to https://github.com/beyonk-adventures/now-sapper-demo. Feedback from a user on Discord:

>still uses now instead of vercel command, has .nowignore instead of .vercelignore, the server.js configuration does not build on now, there is no vercel.json in the root folder (still has now.json)

The user also provided their own sample project that could be an alternative if it's not a priority to update the existing demo: https://github.com/articnet/sapper-vercel

**Comment by antony** [comment]
@benmccann happy to update the demo / accept a PR to update it.

**Comment by thgh** [comment]
An examples folder sounds good to me!
