### ISSUE TITLE
Error! The property `builds` is not allowed in vercel.json – please remove it.

### ISSUE THREAD

**Issue by adnansmajlovic** [thgh/now-sapper#35]
Not sure if they added this just recently, but bulds property can't be part of the vercel.json:

https://vercel.com/docs/configuration?query=builds#project/builds

**NOTE: The builds property has been deprecated in favor of functions. In the majority of cases, you are no longer required to specify a build, instead relying on the build step.**

**Comment by thgh** [comment]
Hmm, that could be the end of this project. Did you find any way around it?

**Comment by thgh** [comment]
Even though I'm using vercel.json I get this warning (and the deploy works)

```Due to `builds` existing in your `now.json` file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-project-settings```

**Comment by antony** [comment]
still working for me too. builds has been deprecated for a while.

**Comment by adnansmajlovic** [comment]
Hm... Doesn't work for me, however it worked when I used "now" instead of "vercel", and it worked with "vercel" on an older project. Also, haven't found a work around yet.

This is what I get with v 19.0.1:

```
$ vercel
Vercel CLI 19.0.1
Error! The property `builds` is not allowed in vercel.json – please remove it.
```
vercel.json:

```json
{
  "version": 2,
  "builds": [
		{
			"src": "package.json",
			"use": "now-sapper"
		}
	],
  "env": {
    "SECRET": "@my-secret-name"
  },
  "functions": {
    "api/test.js": {
      "memory": 1024,
      "maxDuration": 10
    }
  }
}

```

(edit) Reported it to Vercel team, and waiting for a response

**Comment by thgh** [comment]
Looks like you can't mix `builds` and `functions`.

**Comment by adnansmajlovic** [comment]
Yes, thank you Thomas. That was an issue!

**Comment by Ashique20** [comment]
WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings  


I got this problem to how should i fix it

**Comment by antony** [comment]
@Ashique20 I'm assuming that this isn't a new project, what changed between when it worked and now?

**Comment by Ashique20** [comment]
Can we have chat on google meet?


শনি, ৪ মার্চ, ২০২৩ তারিখে ৩:০৩ AM টায় তারিখে Antony Jones <
***@***.***> লিখেছেন:

**Comment by Ashique20** [comment]
Man i really need to solve it and i am totally helpless


শনি, ৪ মার্চ, ২০২৩ তারিখে ১০:৫১ PM টায় তারিখে Ashiqur Rahman Student <
***@***.***> লিখেছেন:
