### ISSUE TITLE
Need to serve statically a folder from `node_modules`

### ISSUE THREAD

**Issue by madacol** [thgh/now-sapper#42]
I made a PR #41 that I think should solve this, but I'm not sure.

I'm using a package that has a folder with images that I want to serve statically.

I made a symbolic link from the static folder to the images folder, but it only works when I deploy from the CLI having that folder whitelisted in `.vercelignore`, but when deploying from github it fails to build because the folder `node_modules` does not exist

**Comment by thgh** [comment]
I don't think that Vercel supports symbolic links, you may get an answer sooner by asking here: https://github.com/vercel/vercel/discussions

Also, do you want the images statically hosted on the CDN or dynamically served through a Lambda?

**Comment by madacol** [comment]
Both options works for me, but at the CDN would be even better.

Thanks

**Comment by thgh** [comment]
How about copying the files on build through package.json? That will bake them into the lambda.
```json
"scripts": {
  "build": "cp -R node_modules/somepkg static/somepkg; sapper build"
```

**Comment by madacol** [comment]
Thank you, never thought about that option
