### ISSUE TITLE
The vercel.json file should be inside of the provided root directory

### ISSUE THREAD

**Issue by ManuelDeLeon** [thgh/now-sapper#45]
I can't deploy my sample app to Vercel. Would you please point me in the right direction?

When I run vercel on my box:
```
Vercel CLI 19.1.1
❗️  The vercel.json file should be inside of the provided root directory.
Error! You defined 1 build that did not match any source files (please ensure they are NOT defined in .vercelignore):
- {"src":"package.json","use":"vercel-sapper"}
```

On Vercel's build log:
```
Cloning github.com/ManuelDeLeon/myproject (Branch: master, Commit: 21dase703) 
WARN: The vercel.json file should exist inside the provided root directory
Cloning completed in 779ms
Analyzing source code...
Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
```
^ this one is extra odd because it's like it doesn't get past `Analyzing source code...`

The project is basically a copy of [a repo by Sveltecasts](https://github.com/sveltecasts/003-auth-ssr-firebase-svelte) with the following changes.

vercel.json
```
{
  "version": 2,
  "builds": [{ "src": "package.json", "use": "vercel-sapper" }]
}
```

src/server.js
```
const app = express()
  .use(...)
  .listen(...);

export default app;
```

.vercelignore
```
__sapper__
node_modules
cypress
```

**Comment by thgh** [comment]
It seems that your package.json and vercel.json are not in the same folder. Do you use both CLI and github integration?

**Comment by ManuelDeLeon** [comment]
Thank you for the quick reply.

_package.json and vercel.json are not in the same folder_
They're both at the root of the project. Unless during deploy they somehow get copied to different places (no clue how that would happen).

_Do you use both CLI and github integration?_
Well right now I'm trying to get either one to work =)

**Comment by ManuelDeLeon** [comment]
The error `The vercel.json file should be inside of the provided root directory.` goes away if I put `vercel.json` on the `src` folder but I still can't deploy.

Locally:
```
Vercel CLI 19.1.1
Error! You defined 1 build that did not match any source files (please ensure they are NOT defined in .vercelignore):
- {"src":"package.json","use":"vercel-sapper"}
```

Vercel's build log:
```
Cloning github.com/ManuelDeLeon/myproject (Branch: master, Commit: 21dase703) 
Cloning completed in 779ms
Analyzing source code...
Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
```

**Comment by thgh** [comment]
Did you resolve the issue?

**Comment by ManuelDeLeon** [comment]
No. I couldn't get it to work =/

**Comment by thgh** [comment]
Based on your Vercel's build log, it looks like it worked successfully.

Looking at your local build, it seems the Vercel config is broken. Try this:
* Remove the `.vercel` folder in your project folder (which contains a package.json that has the sapper dependency)
* Remove any `.vercel` in parent folders of your project folder
* Run `npx vercel-sapper` in your project folder
* Run `vercel` (and answer Yes to the first question)

**Comment by antony** [comment]
Hi @ManuelDeLeon - are you still looking for help with this?

**Comment by ManuelDeLeon** [comment]
No. Thank you.
