### ISSUE TITLE
src/node_modules is not uploaded to vercel

### ISSUE THREAD

**Issue by mightyjol** [thgh/now-sapper#48]
I have critical code in my src/node_modules folder. Sadly i can't find a way to upload this folder.
What is the option to force a folder in the source uploaded?

i tried to specify
!src/node_modules

in my .vercelignore

**Comment by thgh** [comment]
Good question, it has been recently fixed: https://github.com/vercel/vercel/discussions/4624

**Comment by mightyinsomniak** [comment]
thx, solution is to add 

```
!src/node_modules
!src/node_modules/**
```

to .vercelignore
