### ISSUE TITLE
Add support for Sapper with Typescript

### ISSUE THREAD

**Issue by mcmxcdev** [thgh/now-sapper#50]
Currently, `vercel-sapper` is throwing a warning because it is looking for `src/server.js` but the file is actually `server.ts` when using typescript.

Not sure if there would be additional issues to run into, it is my first try setting Sapper up with Vercel.

**Comment by thgh** [comment]
Interesting! Would you like to add support for server.ts? It starts here:
https://github.com/thgh/vercel-sapper/blob/vercel/bin.js#L53

**Comment by mcmxcdev** [comment]
Sure I can take a look at it ;)
