### ISSUE TITLE
baseUrl support

### ISSUE THREAD

**Issue by Jayphen** [thgh/now-sapper#53]
Does this project support `baseUrl` set to anything other than `/`?

I am mounting sapper at `/de` and at `/en`, which sets the `baseUrl` to `/de/` and `/en/` respectively.

When referencing assets, it's thus necessary to use relative rather than absolute paths - for example, in my template.html:

```
    <link rel="stylesheet" href="main.css" />
    <link rel="stylesheet" href="normalize.css" />
```

(note no leading `/`).

This works as intended when building locally, but when deploying to Vercel I get a 404 for those assets (it looks for them at https://domain.com/en/main.css or https://domain.com/de/main.css, and fails) and for the favicon.

**Comment by thgh** [comment]
Are you using https://sapper.svelte.dev/docs#Base_URLs ?
Currently Sapper always sets a <base> tag, so it seems to work as intended.

**Comment by Jayphen** [comment]
Yes, I have configured express as is suggested in the docs.

If you clone the default sapper template, mount sapper at somewhere other than root as described in the docs, and then deploy to vercel, you should be able to reproduce this

**Comment by Jayphen** [comment]
Here's a reproduction doing exactly as I just described

https://github.com/Jayphen/sapper-baseurl
https://sapper-baseurl.vercel.app/de

**Comment by Jayphen** [comment]
Here's a repro

https://github.com/Jayphen/sapper-baseurl
https://sapper-baseurl.vercel.app/de

I just cloned the base sapper template, set the base url to '/de', added vercel-sapper, and deployed. You'll see the manifest, service worker, and some other assets 404.

If you build and run locally, it works fine.

**Comment by thgh** [comment]
Now I see, this builder removes the static assets (and serves them from the CDN) so [this line](https://github.com/Jayphen/sapper-baseurl/blob/master/src/server.js#L13) won't work.

You can include the static assets with the include config: https://github.com/thgh/vercel-sapper#include-files-outside-the-__sapper__-folder which will allow to serve the assets from the Lambda which is probably good enough.

The ultimate solution would be to allow a configuration of multiple basepaths so all static assets are served on all basepaths.

**Comment by thgh** [comment]
Did `config.include` resolve the issue?
