### ISSUE TITLE
Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. 

### ISSUE THREAD

**Issue by migbash** [thgh/now-sapper#61]
![image](https://user-images.githubusercontent.com/20924663/104961336-065faa80-59ce-11eb-988a-e3fd64c28e92.png)

**Comment by kaboomdigital** [comment]
I think Vercel is just warning the user that because the default Sapper `package.json` file has a `build` script attribute it skips any custom Vercel settings. 

In other words: Vercel skips any custom settings you setup in the Build and Development options because of the `package.json` settings. If you want to use custom Vercel settings you would have to remove the `package.json` `build` field. 

Please correct me if I'm wrong.

**Comment by migbash** [comment]
@kaboomdigital makes sense

However, do I need the ```package.json``` in order for the Sapper app to deploy on Vercel, as for the moment it does not even work:

![image](https://user-images.githubusercontent.com/20924663/105618408-a3f81700-5dde-11eb-8006-10bd34ef34dd.png)

And the ```Warning:...``` is the only thing that is shown as to what is causing this error.

However, a simple Single Page Application with just SvelteJS works perfectly, but somehow with Sapper it is does not :/

**Comment by thgh** [comment]
BAD_GATEWAY, that's probably related to https://github.com/thgh/vercel-sapper/issues/56#issuecomment-762806855

**Comment by fred-snyder** [comment]
@migbash Yes you do need `package.json`

```
{
  "version": 2,
  "builds": [
    {
      "src": "package.json", // as stated here in `vercel.json`
      "use": "vercel-sapper"
    }
  ]
}
```

I remember running into the same/similar error

Decided to re-setup my project from scratch. When I retried I realized a step in the config wasn't setup successful (setting up `src/server.js`) (perhaps I accidentally discarded the changes 🤨)

```bash
# so don't forget to run this before deploying
# this creates a `vercel.json` and a `.vercelignore` and patches `src/server.js`
npx vercel-sapper
```

Hope it helps.

**Comment by migbash** [comment]
@thgh @fred-snyder no success with either solution. If you deploy a simple sapper ```npx degit "sveltejs/sapper-template#rollup" my-app```, on to vercel, does it work for you when using ```npx vercel-sapper```?

**Comment by fred-snyder** [comment]
> 
> 
> @thgh @fred-snyder no success with either solution. If you deploy a simple sapper `npx degit "sveltejs/sapper-template#rollup" my-app`, on to vercel, does it work for you when using `npx vercel-sapper`?

Yes. All the default settings work. I use the Vercel CLI.

**Comment by migbash** [comment]
@fred-snyder huh 🤔, ok let me have a try once more.

**Comment by thgh** [comment]
I will close this for now as that warning has been there for almost a year (since Vercel introduced the Project Settings in the dashboard).
This project was broken for a couple months because of the .vercelignore file, but that was fixed two weeks ago 😃

**Comment by nosirbekdev** [comment]
![image](https://github.com/thgh/vercel-sapper/assets/79135844/e8d5f821-b9af-4735-b1e5-f0e159744d00)

django build warning?

**Comment by emanuel-flexo** [comment]
resolved this?

**Comment by Shahan786developer** [comment]
> ![image](https://user-images.githubusercontent.com/79135844/268506572-e8d5f821-b9af-4735-b1e5-f0e159744d00.png)
> 
> django build warning?

**Comment by Shahan786developer** [comment]
I when deploy my django, project i cant see my static files, can anyone help??

**Comment by jomhar823** [comment]
> ![image](https://user-images.githubusercontent.com/79135844/268506572-e8d5f821-b9af-4735-b1e5-f0e159744d00.png)
> 
> django build warning?

i also have the same problem can you provide me an assistance for that? thanks

**Comment by 1atul0** [comment]
![image](https://github.com/thgh/vercel-sapper/assets/82318645/536af66a-fa5d-4ccd-84da-5d8d434f5d76)
I also get the same error.
I have used: Node.js, express.js and Ejs and dotenv file
this is my github file:- https://github.com/1atul0/Basic_Banking_system
and this is verce.json file:- 
![image](https://github.com/thgh/vercel-sapper/assets/82318645/73b9d5f3-8447-4e76-8a4f-2c844619d1af)

**Comment by thgh** [comment]
It's probably best to create an issue in the Vercel org. This repo is related to sapper.

**Comment by Giasinit** [comment]
is there any updates?

**Comment by Arpit-Yadav-Dev** [comment]
![Screenshot 2024-02-16 215244](https://github.com/thgh/vercel-sapper/assets/142081471/71dc808c-0181-49c7-9cc6-3fa87e1368ba)

Facing the same issue i uploaded my express app and build folder is inside the express app . Don't know what's the issue .

**Comment by Giasinit** [comment]
So it's simple.
certain libraries cannot be used in vercel.
My solutions have been to change certain libraries or even use:

// vercel.json
```
{
    "version": 2,
    "builds": [
        {
            "src": "package.json",
            "use": "vercel-sapper"
        },
        {
            "src": "index.js",
            "use": "@vercel/node"
        }
    ],
    "routes": [
        {
            "src": "/(.*)",
            "dest": "index.js",
            "methods": ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
            "headers": {
                "Access-Control-Allow-Origin": "*"
            }
        }
    ]
}
```

**Comment by Ernesto-Alves67** [comment]
I'm getting this error, trying to host an API on FastAPI.

![imagem](https://github.com/thgh/vercel-sapper/assets/98620218/5db4c54f-4bea-42c7-9b7a-14591fdbb913)

And this log on vercel's logs page. 
 ```
 LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 202, in __call__
    self.app_queue = asyncio.Queue(loop=loop)
 ```
 
 > Repo: https://github.com/Ernesto-Alves67/fastAPI_teste

**Comment by slightlee** [comment]
> I'm getting this error, trying to host an API on FastAPI. 重试    错误原因
> 
> ![imagem](https://private-user-images.githubusercontent.com/98620218/329821264-5db4c54f-4bea-42c7-9b7a-14591fdbb913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTAwOTUsIm5iZiI6MTcxNjQ0OTc5NSwicGF0aCI6Ii85ODYyMDIxOC8zMjk4MjEyNjQtNWRiNGM1NGYtNGJlYS00MmM3LTliN2EtMTQ1OTFmZGJiOTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA3MzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNTZhNWQwNTIzMDRmNjE0MzFiZDFlYTFhOGQwMmRmYWI1ZGJiM2Y1YzJkYjE3NWVlZDAyOTIwNzQ1ZTM4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yh1kmJZM9iTtdC-icWQHnmXmqq_nxRZ7M4zh6MORPis)
> 
> And this log on vercel's logs page. 重试    错误原因
> 
> ```
> LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
> [ERROR] TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
> Traceback (most recent call last):
>  File "/var/task/vc__handler__python.py", line 305, in vc_handler
>    response = asgi_cycle(__vc_module.app, body)
>  File "/var/task/vc__handler__python.py", line 202, in __call__
>    self.app_queue = asyncio.Queue(loop=loop)
> ```
> 
> > Repo: https://github.com/Ernesto-Alves67/fastAPI_teste

I also encountered the same problem when using FastAPI. Have you resolved it ?

**Comment by Ernesto-Alves67** [comment]
I couldn't resolved yet.

**Comment by Shamonti** [comment]
> ![Screenshot 2024-02-16 215244](https://private-user-images.githubusercontent.com/142081471/305477727-71dc808c-0181-49c7-9cc6-3fa87e1368ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTc3MjQsIm5iZiI6MTcxNzQ5NzQyNCwicGF0aCI6Ii8xNDIwODE0NzEvMzA1NDc3NzI3LTcxZGM4MDhjLTAxODEtNDljNy05Y2M2LTNmYTg3ZTEzNjhiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMDM3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2MxMDg1NjgxNjJlODU0NWJlZTY1MDE1YTg4YjA1ZjFiOGFiMjg4ZTM0ZDQ0MWY0NWE3YWI5NzAyY2U4MjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNSXv3927hJ2WAzTZrDoA8htnm91Veal1VuRHoF8auU)
> 
> Facing the same issue i uploaded my express app and build folder is inside the express app . Don't know what's the issue .

Facing the same issue with my django app.

**Comment by Ernesto-Alves67** [comment]
> > ![Screenshot 2024-02-16 215244](https://private-user-images.githubusercontent.com/142081471/305477727-71dc808c-0181-49c7-9cc6-3fa87e1368ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTc3MjQsIm5iZiI6MTcxNzQ5NzQyNCwicGF0aCI6Ii8xNDIwODE0NzEvMzA1NDc3NzI3LTcxZGM4MDhjLTAxODEtNDljNy05Y2M2LTNmYTg3ZTEzNjhiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMDM3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2MxMDg1NjgxNjJlODU0NWJlZTY1MDE1YTg4YjA1ZjFiOGFiMjg4ZTM0ZDQ0MWY0NWE3YWI5NzAyY2U4MjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNSXv3927hJ2WAzTZrDoA8htnm91Veal1VuRHoF8auU)
> > Facing the same issue i uploaded my express app and build folder is inside the express app . Don't know what's the issue .
> 
> Facing the same issue with my django app.

I think tha we shoul start a new discurssion, are nobody want help anymore.

**Comment by caiomadeira** [comment]
is there a link to the new discussion?

**Comment by nisharga** [comment]
Still facing same issue and wonder no one can fix it :octocat:

**Comment by slightlee** [comment]
> Still facing same issue and wonder no one can fix it :octocat:

I have solved this problem. This issue is related to the Node. js version of Vercel, which is an incredible thing. Use Node.js to configure the lowest version possible.

**Comment by Innavoj** [comment]
Please, can someone help me solve this problem in vercel
 

This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: fra1:lhr1::85kzp-1719464449663-222b593a5bd6

**Comment by s-smits** [comment]
Same problem, followed clear instructions to fix Serverless > 250MB issue, but now running into this issue.

**Comment by BCK2BCK** [comment]
we all know that out code works because it shows up in github webpage .io so wth is wrong with vercel

**Comment by shaniCoder21** [comment]
I am deploying the Node.js application on Vercel, but I am getting an error. How can I resolve this issue?

![image](https://github.com/user-attachments/assets/bc272a07-3b92-4417-bff6-acdf25bedc45)

**Comment by Ernesto-Alves67** [comment]
> I am deploying the Node.js application on Vercel, but I am getting an error. How can I resolve this issue?
> 
> ![image](https://private-user-images.githubusercontent.com/170647785/388541422-bc272a07-3b92-4417-bff6-acdf25bedc45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTM5NTUsIm5iZiI6MTczMjIxMzY1NSwicGF0aCI6Ii8xNzA2NDc3ODUvMzg4NTQxNDIyLWJjMjcyYTA3LTNiOTItNDQxNy1iZmY2LWFjZGYyNWJlZGM0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxODI3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDg4ODg3MGM5NzM0ZjMwOTNlODYzMGY3N2VlM2FkN2IzOGIwNjEyYTc4MmM3YmFlM2RlOTA5MGY3ZGRmN2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cIHKpyBZesKDklqwrEbkkUYvYMz3YdLssWFDv06Gh7c)

I have the same error once, here there is no one that can help with this. :\

**Comment by DCpraise** [comment]
Use a vercel configuration file like vercel.json the in it set rewrites properties check it on YouTube for future explanation

**Comment by vivasun01822** [comment]
> So it's simple. certain libraries cannot be used in vercel. My solutions have been to change certain libraries or even use:
> 
> // vercel.json
> 
> ```
> {
>     "version": 2,
>     "builds": [
>         {
>             "src": "package.json",
>             "use": "vercel-sapper"
>         },
>         {
>             "src": "index.js",
>             "use": "@vercel/node"
>         }
>     ],
>     "routes": [
>         {
>             "src": "/(.*)",
>             "dest": "index.js",
>             "methods": ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
>             "headers": {
>                 "Access-Control-Allow-Origin": "*"
>             }
>         }
>     ]
> }
> ```

**It is working** **Thanks bro @Giasinit**

**Comment by EkowYamoah** [comment]
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: cpt1::j8css-1739550622122-3ec4fd83b62b

If you are a visitor, contact the website owner or try again later.
If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED) and [check the logs](https://booking-website-kae885sui-ekow-yamoahs-projects.vercel.app/_logs?requestId=cpt1::j8css-1739550622122-3ec4fd83b62b).


Did anyone find a solution to this issue?
I am trying to deploy a django app.

**Comment by azeem-ocs** [comment]
> I'm getting this error, trying to host an API on FastAPI.
> 
> ![imagem](https://github.com/thgh/vercel-sapper/assets/98620218/5db4c54f-4bea-42c7-9b7a-14591fdbb913)
> 
> And this log on vercel's logs page.
> 
> ```
> LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
> [ERROR] TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
> Traceback (most recent call last):
>  File "/var/task/vc__handler__python.py", line 305, in vc_handler
>    response = asgi_cycle(__vc_module.app, body)
>  File "/var/task/vc__handler__python.py", line 202, in __call__
>    self.app_queue = asyncio.Queue(loop=loop)
> ```
> 
> > Repo: https://github.com/Ernesto-Alves67/fastAPI_teste

This error can occur due to multiple reasons.
I was able to solve this error by looking at the project logs.
For example, I was trying to create a log file at the root.

**Comment by darde** [comment]
I just removed the `.vercel` directory and ran `vercel` again, and it worked for me.

**Comment by jz2010927** [comment]
> I just removed the `.vercel` directory and ran `vercel` again, and it worked for me.

This worked for me, thanks!
