### ISSUE TITLE
i cannot deploy api graphql node to vercel error 

### ISSUE THREAD

**Issue by Wil-Quispe** [thgh/now-sapper#65]
2021-03-13T00:34:40.968Z	undefined	ERROR	Cannot find module './resolvers/Query'
Require stack:
- /var/task/dist/main.js
- /var/task/___vc_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
2021-03-13T00:34:40.968Z	undefined	ERROR	Did you forget to add it to "dependencies" in `package.json`?
RequestId: 3d09aa0c-790f-4184-8eaf-8eb62217165c Error: Runtime exited with error: exit status 1
Runtime.ExitError

![image_2021-03-12_193923](https://user-images.githubusercontent.com/73201460/111012626-a56ba780-836a-11eb-805f-3a9fe78d5457.png)
![image_2021-03-12_194055](https://user-images.githubusercontent.com/73201460/111012682-dcda5400-836a-11eb-9d7a-d705d85c5b94.png)

![image_2021-03-12_194151](https://user-images.githubusercontent.com/73201460/111012727-fda2a980-836a-11eb-94a9-c2b6fb6472e1.png)
![image_2021-03-12_194209](https://user-images.githubusercontent.com/73201460/111012744-085d3e80-836b-11eb-999c-1c2661fd25c9.png)
![image_2021-03-12_194226](https://user-images.githubusercontent.com/73201460/111012759-127f3d00-836b-11eb-9dff-4d387f219dd8.png)

**Comment by thgh** [comment]
Even though I'm interested, this does not belong here, check out [vercel discussions](https://github.com/vercel/vercel/discussions)

Always welcome to share your insights here 😉
