### ISSUE TITLE
Static assets not being applied on node app on vercel

### ISSUE THREAD

**Issue by snehathakur07** [thgh/now-sapper#70]
![image](https://github.com/thgh/vercel-sapper/assets/98324142/cac95c12-014e-46e1-b332-b7fcf9cc3627)
This is my project, a portfolio website, when im deploying it on vercel, only the html file is loading none of the static assets are loading, for styles.css, the console throws "Refused to apply style from 'https://sneha-thakur-rf8eol8eg-snehathakur07s-projects.vercel.app/styles/styles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled." theres an error for every static asset(css , js, images etc)

**Comment by thgh** [comment]
I'm not affiliated with Vercel, you could ask on https://github.com/vercel/vercel
