### ISSUE TITLE
Vercel Buildings problems.

### ISSUE THREAD

**Issue by Ernesto-Alves67** [thgh/now-sapper#71]
Please, can someone help me solve this problem in vercel

This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: fra1:lhr1::85kzp-1719464449663-222b593a5bd6

**Comment by thgh** [comment]
Are you using sapper?

**Comment by thgh** [comment]
Hi, I'm not affiliated with Vercel, you are looking for https://vercel.com/help
