### ISSUE TITLE
404 not found. in vercel deployment, could someone help me !!!

### ISSUE THREAD

**Issue by kalkeesh** [thgh/now-sapper#72]
when i deploy my vercel app in python, i got this 404 error, sould some one help me !! please !
![Screenshot 2024-10-02 113125](https://github.com/user-attachments/assets/1e36674f-55ed-4a1c-9cbb-9ad8320753e4)

**Comment by thgh** [comment]
Hi, I'm not affiliated with Vercel, you are looking for https://vercel.com/help
